spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 1000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: Asia/Seoul
jwt:
  token:
    secretKey: ${JWT_TOKEN_SECRET_KEY}
    expiration:
      access: 14400000 # 4시간
      refresh: 1209600000 # 2주 (예시)

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      path:
        chat : chats
        discount : discounts
        life-tip : life-tips
        local-food : local-foods
        profile : profiles
        review : reviews
        purchase : purchase
        share : share
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}